<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>0.5.0.0</AssemblyVersion>
    <FileVersion>0.5.0.0</FileVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BnkExtractor\BnkExtractor\BnkExtractor.csproj" />
    <ProjectReference Include="..\StarfieldVT.Core\StarfieldVT.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.7" />
    <PackageReference Include="FFMpegCore" Version="5.1.0" />
    <PackageReference Include="LibVLCSharp" Version="3.9.3" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

</Project>
